
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Sanjib Mondal"
title_separator          : "-"
name                     : "Sanjib Mondal"
description              : "Data Science Portfolio"
url                      : "https://Sanjib-Mondal.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "Sanjib-Mondal/Sanjib-Mondal.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
